### ISSUE TITLE
Merge lock support

### ISSUE THREAD

**Issue by dkocher** [dCache/nfs4j#42] opened 2017-02-01 14:22 UTC
Are there any plans to merge the lock support in https://github.com/kofemann/nfs4j/tree/lock-locku to the current master. Since the recent changes in b873c76 the branch can no longer be applied to master without conflicts.

**Comment by kofemann** [comment] 2017-02-01 14:32
I have rebased lock-locku branch on top of current master. The lock support is under testing, and when review process will be complete, the locking code will be merge into the master branch.

Do you  use locking? If is NFSv4.0 or v4.1?

**Comment by dkocher** [comment] 2017-02-01 14:40
Just fetched your rebased branch, awesome. We use the lock support in production with NFS 4.0 for interoperability with Microsoft Office and other applications writing to a mount.

**Comment by kofemann** [comment] 2017-02-01 14:43
Cool! Can you tell me which nfs client is used with windows?

-kofemann

**Comment by dkocher** [comment] 2017-02-01 14:44
We do not rely on nfs4j on Windows.

**Comment by dkocher** [comment] 2017-02-01 14:53
(Off topic) Do you have any information if there is NFS4.1 client support on macOS?

**Comment by kofemann** [comment] 2017-02-01 15:26
No. osx supports (with quite number of bugs) only v4.0. On the other hand,
they use code based on freebds unix, so eventually this code will be merged
as well.

-kofemann
/** caffeinated mutations of the core personality */

**Comment by dkocher** [comment] 2017-02-05 19:28
Just wanted to follow up on the rebased lock support branch https://github.com/kofemann/nfs4j/tree/lock-locku. In my testing, I have seen `State not known to the client:` errors with a stacktrace originating from `OperationLOCK:96`. There is possibly a regression from merging with the latest state management refactorings?

**Comment by kofemann** [comment] 2017-02-05 21:03
Hi,

Can you provide the stacktrace or a part of it?

-kofemann
/** caffeinated mutations of the core personality */

**Comment by dkocher** [comment] 2017-02-05 21:34
I will reproduce the issue tomorrow and provide some debug logging and stacktrace.

**Comment by dkocher** [comment] 2017-02-07 14:27
Attached the `DEBUG` log with the `LOCK : NFS4ERR_BAD_STATEID` error.

[nfs4j-issue-42.log.txt](https://github.com/dCache/nfs4j/files/757929/nfs4j-issue-42.log.txt)

**Comment by kofemann** [comment] 2017-02-07 14:31
Thanks for update!

looks like osx client. did you run a particular test? is it always reproducible or you need to run multiple iterations to hit it?

**Comment by dkocher** [comment] 2017-02-07 14:33
The client is macOS 10.12. This is reproducible opening a mounted volume in Finder.app.

**Comment by kofemann** [comment] 2017-02-08 16:10
Ok. I am able to reproduce it. Either I misinterpreted the NFS spec, or osx client is broken.
I have pinged IETF nfs4 working group to clarify server/client incompatibility. Technically,
if server is broken - I can fix it. If the problem in the client, then .... probably I have to add
 some workaround, as client fixes always a pain, especially with osx.

**Comment by kofemann** [comment] 2017-02-08 17:06
merged in 10f7918. 
Please open a new issue to followup on osx issue.

**Closed by kofemann** 2017-02-08 17:06 UTC
Labels: question
